### ISSUE TITLE
Project is working?

### ISSUE THREAD

**Issue by hanc2006** [ionited/fiber#3]
Hey,

I am trying to use your router, following the instructions on the README file but the I think that middlewares are registered in a  wrong way. Any suggestions?

![CleanShot 2023-11-22 at 18 19 47@2x](https://github.com/ionited/fiber/assets/4517251/539f029c-4985-4d2c-938f-e5c586e93ee2)

**Comment by gabrielcursino** [comment]
Hello @hanc2006, Thank you for your feedback!

This problem was fixed on the latest release [0.4.1](https://github.com/ionited/fiber/releases/tag/0.4.1)

**Comment by hanc2006** [comment]
I did the same changes 🤣.
Thank's
