### ISSUE TITLE
Fiber golang vs js

### ISSUE THREAD

**Issue by ReneWerner87** [ionited/fiber#4]
Was this framework named after ours on purpose ? Maybe you should come up with a different name to avoid conflicts with our projects

https://docs.gofiber.io/
https://github.com/gofiber/fiber
https://gofiber.io/
![image](https://github.com/ionited/fiber/assets/7063188/bc0618b4-6640-486f-a4b8-d3504c157d5e)

**Comment by gabrielcursino** [comment]
Hello!

No, i didn't know your project.

I will try to think of another name, but i think there will be no conflicts, because they are from different languages and different communities.

**Comment by ReneWerner87** [comment]
everyone actually only talks about fiber and not gofiber(its just the repo name), so confusion still happens
see the dev articles https://github.com/gofiber/awesome-fiber?tab=readme-ov-file#-articles

is still confusing for everyone when another framework is called that, despite the different language
since you don't have a stable version 1 yet, a name swap would make sense

**Comment by Fenny** [comment]
@gabrielcursino any updates on this?

It's causing some confusion, is it possible to rename it to fiberjs?

**Comment by gabrielcursino** [comment]
Hello @ReneWerner87 @Fenny! Sorry for the delay.

I've renamed the project from Fiber to Mesh to avoid confusion with your project.
